apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: analytics
  name: rstudio1
spec:
  selector:
    matchLabels:
      app: rstudio1
  serviceName: rstudio1
  replicas: 1
  template:
    metadata:
      labels:
        app: rstudio1
    spec:
      #securityContext:
      #    runAsUser: 1000
      #    fsGroup: 1000
      #    runAsNonRoot: true
      containers:
      - image: "image-registry.internal.ccp.systems/paas/ccp-up4a-rocker:v0.9"
      #- image: "eu.gcr.io/ccp-testenv/rstudio"
#        command: ["/bin/sh","-c"]
 #       args: ["/sbin/my_init"]
        imagePullPolicy: Always
        name: rstudio1
        resources:
          requests:
            memory: "1024Mi"
            cpu: "200m"
        #readinessProbe:
        #  tcpSocket:
        #    port: 7077
        #  timeoutSeconds: 5
        #  periodSeconds: 5
        #  initialDelaySeconds: 30
        #livenessProbe:
        #  tcpSocket:
        #     port: 7077
        # timeoutSeconds: 5
        #  periodSeconds: 5
        #  initialDelaySeconds: 60
        ports:
        - containerPort: 8787
          name: http
        #volumeMounts:
        #    - name: rstudio-master
        #      mountPath: /opt/spark/boot-spark-master.sh
        #      subPath: boot-spark-master.sh
      #volumes:
      #- name: boot-spark-master
      #  configMap:
      #    name: boot-spark-master

