apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  namespace: analytics
spec:
  ports:
  - port: 8787
    targetPort: 9376
    protocol: TCP
  selector:
    app: rstudio-server 
  type: LoadBalancer
