apiVersion: v1
kind: Service
metadata:
 namespace: analytics
 name: rstudio1
spec:
 type: LoadBalancer
 selector:
  statefulset.kubernetes.io/pod-name: rstudio1
 ports:
 - protocol: TCP
   port: 8787
   name: http
